- name: "Local setup"
  hosts: localhost
  connection: local 
  tasks:
  - name: Install nvm
    ansible.builtin.shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  - name: Install nodejs && npm
    ansible.builtin.shell: >
      source ~/.nvm/nvm.sh && nvm install --lts
    args:
      executable: /bin/bash

