- name: "Local dev setup"
  hosts: localhost
  connection: local 
  tasks:
    - import_tasks: ubuntu/setup.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - import_tasks: macos/setup.yml
      when: ansible_distribution == 'MacOSX'
    - import_tasks: common/setup.yml

