# [window]
# startup_mode = "Maximized"
import = [
    "~/.config/alacritty/themes/themes/breezy.toml"
]

[font]
size = 9

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Copy" },
]

