# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export LC_ALL=en_US.UTF-8

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# omz options
HYPHEN_INSENSITIVE="true"
ENABLE_CORRECTION="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

## additional nvim config aliases
alias vim="nvim"
alias vi="nvim"
alias v="nvim"

# reloading alias
alias rl_tmux="tmux source ~/.tmux.conf"
alias rl_zsh="source ~/.zshrc"

# layzgit
alias lg="lazygit"

export PATH=$PATH:$HOME/.local/bin

if [ -f ~/dev/.zshenv ]; then
  source ~/dev/.zshenv
else
  print "zshenv for dev not found"
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval "$(zoxide init zsh)"

[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

[ -f $HOME/.cargo/env ] && source $HOME/.cargo/env

# add neovim to path
export PATH=$HOME/.neovim/v0.9.2/bin:$PATH

# add dotfiles/bin and go/bin to path
export PATH=$HOME/dotfiles/bin:$HOME/go/bin:$PATH

[ -f "/usr/local/opt/openjdk@17/bin/java" ] && export PATH="/usr/local/opt/openjdk@17/bin":$PATH
[ -f "/usr/lib/jvm/default-runtime/bin/java" ] && export PATH="/usr/lib/jvm/default-runtime/bin/java":$PATH

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
