export LC_ALL=en_US.UTF-8

setopt PROMPT_SUBST

# Path to your oh-my-zsh installation.
# export ZSH="$HOME/.oh-my-zsh"

# theme
# ZSH_THEME="powerlevel10k/powerlevel10k"

# omz options
# HYPHEN_INSENSITIVE="true"
# ENABLE_CORRECTION="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# plugins=(zsh-autosuggestions zsh-syntax-highlighting)

export HISTFILE=$HOME/.zsh_history
autoload -U compinit; compinit

## additional nvim config aliases
alias vim="nvim"
alias vi="nvim"
alias v="nvim"
# layzgit
alias lg="lazygit"

export PATH=$PATH:$HOME/.local/bin

if [ -f ~/dev/.zshenv ]; then
  source ~/dev/.zshenv
else
  print "zshenv for dev not found"
fi

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval "$(zoxide init zsh)"

[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh
# [ -f $HOME/.cargo/env ] && source $HOME/.cargo/env

# add neovim, dotfiles/bin and go/bin to path
export PATH=$HOME/.neovim/v0.9.2/bin:$HOME/dotfiles/bin:$HOME/go/bin:$PATH

# [ -f "/usr/local/opt/openjdk@17/bin/java" ] && export PATH="/usr/local/opt/openjdk@17/bin":$PATH
# [ -f "/usr/lib/jvm/default-runtime/bin/java" ] && export PATH="/usr/lib/jvm/default-runtime/bin/java":$PATH
#
source $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

export PROMPT='%F{yellow}%~ %F{red}>%F{reset_color} '

